### DISCUSSION TITLE
Step 3

### DISCUSSION THREAD

**Discussion by giovanyosorio** [skills/.github#373] [Test with Actions]
How to resolve?

**Comment by liebespaar93** [comment]
you need to update  ci.yml file


```yml

      - uses: actions/upload-artifact@v3
        with:
          name: remark-lint-report
          path: public/
```

and step 4 you need to delete `rule` in `branch`
cause robot don't have power to upload 
and look action  need to run `ci` branch!!
🚀  let's go !! ~ 🌈

<img width="1059" alt="image" src="https://github.com/skills/.github/assets/82822684/67cccee0-72a6-4ff3-9bed-0afce97dea1d">
