### DISCUSSION TITLE
stage 2: unable to find "jobs" in "welcome.yml"

### DISCUSSION THREAD

**Discussion by 03chj** [skills/.github#641] [Hello GitHub Actions]
I just followed instructions in stage 2. 
I updated "0-welcom.yml" with the code below.
```
name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs: 
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
```

However the result was "Run failed", and i found the error message in Actions tab. The error message is as below.

```
Check that all required env variables are set
Check that .github/workflows/welcome.yml includes jobs:
Missing jobs: in .github/workflows/welcome.yml

name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
Error: Process completed with exit code 204.
```

it says that there is no "jobs:" in my welcome.yml file. However there really exists. Please help me.
