### DISCUSSION TITLE
continuous-delivery-azure step two check appears broken

### DISCUSSION THREAD

**Discussion by housten** [skills/.github#71] [Q&A]
I am working my way through continuous-delivery-azure step and the following job in 2-setup-azure-environment.yml fails. 

```
      # Create pull request from azure-configuration branch to set up next step
      - name: Create azure-configuration pull request 
        run: ./.github/script/create-workflow-pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: azure-configuration
          PR_TITLE: 'Added spinup-destroy.yml workflow'
 ```         
 The job appears to expect there to be an azure-configuration branch but there is no reference in the readme file to azure-configuration. So the branch doesn't exist but the script attempts to check it in and fails with the error:
 `pull request create failed: GraphQL: Head sha can't be blank, Base sha can't be blank, No commits between main and azure-configuration, Head ref must be a branch (createPullRequest)`
 
The script allows for a pull-first, which would create the branch via a git checkout command - but nothing is added to the branch so the pr creation should fail because there won't be any differences between azure-configuration and main. The PR_Title sent to the action is "Added spinup-destroy.yml workflow" but there is no sign of a yml file by that name.
 
 There is a thread from early august about this same issue that remains unanswered therefore I am creating a new discussion hoping to catch the eye of the skill maintainers...
